"""initial schema

Revision ID: 00bc6d5f7fc3
Revises:
Create Date: 2026-07-18 12:32:56.566068
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "00bc6d5f7fc3"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("dataset", sa.String(length=48), nullable=False),
        sa.Column("run_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("rows_ingested", sa.Integer(), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ingestion_runs_dataset"), "ingestion_runs", ["dataset"], unique=False)
    op.create_index(
        op.f("ix_ingestion_runs_run_date"), "ingestion_runs", ["run_date"], unique=False
    )
    op.create_index(op.f("ix_ingestion_runs_source"), "ingestion_runs", ["source"], unique=False)
    op.create_table(
        "securities",
        sa.Column("isin", sa.String(length=12), nullable=False),
        sa.Column("instrument_type", sa.String(length=8), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("issuer", sa.Text(), nullable=True),
        sa.Column("coupon", sa.Float(), nullable=True),
        sa.Column("maturity_date", sa.Date(), nullable=True),
        sa.Column("face_value", sa.Float(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("first_seen", sa.Date(), nullable=False),
        sa.Column("last_seen", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("isin"),
    )
    op.create_index(
        op.f("ix_securities_instrument_type"), "securities", ["instrument_type"], unique=False
    )
    op.create_index(op.f("ix_securities_issuer"), "securities", ["issuer"], unique=False)
    op.create_index(
        op.f("ix_securities_maturity_date"), "securities", ["maturity_date"], unique=False
    )
    op.create_table(
        "security_attribute_history",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("isin", sa.String(length=12), nullable=False),
        sa.Column("attribute", sa.String(length=48), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("isin", "attribute", "valid_from", name="uq_attr_history_point"),
    )
    op.create_index(
        op.f("ix_security_attribute_history_attribute"),
        "security_attribute_history",
        ["attribute"],
        unique=False,
    )
    op.create_index(
        op.f("ix_security_attribute_history_isin"),
        "security_attribute_history",
        ["isin"],
        unique=False,
    )
    op.create_table(
        "valuations",
        sa.Column("isin", sa.String(length=12), nullable=False),
        sa.Column("quote_date", sa.Date(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("instrument_type", sa.String(length=8), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("coupon", sa.Float(), nullable=True),
        sa.Column("maturity_date", sa.Date(), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("ytm", sa.Float(), nullable=True),
        sa.Column(
            "loaded_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("isin", "quote_date", "source"),
    )
    op.create_index(
        op.f("ix_valuations_instrument_type"), "valuations", ["instrument_type"], unique=False
    )
    op.create_index(op.f("ix_valuations_quote_date"), "valuations", ["quote_date"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_valuations_quote_date"), table_name="valuations")
    op.drop_index(op.f("ix_valuations_instrument_type"), table_name="valuations")
    op.drop_table("valuations")
    op.drop_index(
        op.f("ix_security_attribute_history_isin"), table_name="security_attribute_history"
    )
    op.drop_index(
        op.f("ix_security_attribute_history_attribute"), table_name="security_attribute_history"
    )
    op.drop_table("security_attribute_history")
    op.drop_index(op.f("ix_securities_maturity_date"), table_name="securities")
    op.drop_index(op.f("ix_securities_issuer"), table_name="securities")
    op.drop_index(op.f("ix_securities_instrument_type"), table_name="securities")
    op.drop_table("securities")
    op.drop_index(op.f("ix_ingestion_runs_source"), table_name="ingestion_runs")
    op.drop_index(op.f("ix_ingestion_runs_run_date"), table_name="ingestion_runs")
    op.drop_index(op.f("ix_ingestion_runs_dataset"), table_name="ingestion_runs")
    op.drop_table("ingestion_runs")
    # ### end Alembic commands ###
