"""idempotency unique constraints on runs and dq checks

Revision ID: 45cb274a85f3
Revises: 522a4940aab4
Create Date: 2026-07-18 14:38:54.905014
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "45cb274a85f3"
down_revision: str | None = "522a4940aab4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Collapse pre-existing duplicates (from prior append-mode runs) before adding the unique keys,
    # keeping the most-recent row (max id) per key.
    op.execute(
        "DELETE FROM data_quality_checks a USING data_quality_checks b "
        "WHERE a.id < b.id AND a.dataset = b.dataset AND a.run_date = b.run_date "
        "AND a.check_name = b.check_name"
    )
    op.execute(
        "DELETE FROM ingestion_runs a USING ingestion_runs b "
        "WHERE a.id < b.id AND a.source = b.source AND a.dataset = b.dataset "
        "AND a.run_date = b.run_date"
    )
    op.create_unique_constraint(
        "uq_data_quality_check", "data_quality_checks", ["dataset", "run_date", "check_name"]
    )
    op.create_unique_constraint(
        "uq_ingestion_run", "ingestion_runs", ["source", "dataset", "run_date"]
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_ingestion_run", "ingestion_runs", type_="unique")
    op.drop_constraint("uq_data_quality_check", "data_quality_checks", type_="unique")
    # ### end Alembic commands ###
