"""trades table

Revision ID: 522a4940aab4
Revises: bed81f16f24a
Create Date: 2026-07-18 13:57:56.371756
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "522a4940aab4"
down_revision: str | None = "bed81f16f24a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trades",
        sa.Column("isin", sa.String(length=12), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("segment", sa.String(length=24), nullable=False),
        sa.Column("descriptor", sa.Text(), nullable=True),
        sa.Column("ltp", sa.Float(), nullable=True),
        sa.Column("lty", sa.Float(), nullable=True),
        sa.Column("no_of_trades", sa.Integer(), nullable=True),
        sa.Column("trade_value", sa.Float(), nullable=True),
        sa.Column("wap", sa.Float(), nullable=True),
        sa.Column("way", sa.Float(), nullable=True),
        sa.Column(
            "loaded_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint("ltp IS NULL OR ltp > 0", name="ck_trade_ltp_positive"),
        sa.PrimaryKeyConstraint("isin", "trade_date", "source", "segment"),
    )
    op.create_index(op.f("ix_trades_trade_date"), "trades", ["trade_date"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trades_trade_date"), table_name="trades")
    op.drop_table("trades")
    # ### end Alembic commands ###
