"""data quality: interest_type, dq checks table, constraints

Revision ID: 55fdc87faa72
Revises: 00bc6d5f7fc3
Create Date: 2026-07-18 13:13:05.912559
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "55fdc87faa72"
down_revision: str | None = "00bc6d5f7fc3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_quality_checks",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("dataset", sa.String(length=48), nullable=False),
        sa.Column("run_date", sa.Date(), nullable=False),
        sa.Column("check_name", sa.String(length=48), nullable=False),
        sa.Column("level", sa.String(length=8), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("observed", sa.Float(), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_data_quality_checks_check_name"),
        "data_quality_checks",
        ["check_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_quality_checks_dataset"), "data_quality_checks", ["dataset"], unique=False
    )
    op.create_index(
        op.f("ix_data_quality_checks_run_date"), "data_quality_checks", ["run_date"], unique=False
    )
    op.create_index(
        op.f("ix_data_quality_checks_source"), "data_quality_checks", ["source"], unique=False
    )
    op.add_column("securities", sa.Column("interest_type", sa.String(length=24), nullable=True))
    # ### end Alembic commands ###

    # CHECK constraints (value sanity backstops)
    op.create_check_constraint(
        "ck_security_coupon_nonneg", "securities", "coupon IS NULL OR coupon >= 0"
    )
    op.create_check_constraint(
        "ck_valuation_price_positive", "valuations", "price IS NULL OR price > 0"
    )
    op.create_check_constraint("ck_valuation_ytm_nonneg", "valuations", "ytm IS NULL OR ytm >= 0")

    # active_securities view: the "investable now" universe (not matured, still ACTIVE).
    op.execute(
        """
        CREATE OR REPLACE VIEW active_securities AS
        SELECT s.*
        FROM securities s
        LEFT JOIN LATERAL (
            SELECT value FROM security_attribute_history h
            WHERE h.isin = s.isin AND h.attribute = 'security_status' AND h.valid_to IS NULL
            LIMIT 1
        ) st ON true
        WHERE (s.maturity_date IS NULL OR s.maturity_date >= CURRENT_DATE)
          AND (st.value IS NULL OR upper(st.value) = 'ACTIVE')
        """
    )


def downgrade() -> None:
    op.execute("DROP VIEW IF EXISTS active_securities")
    op.drop_constraint("ck_valuation_ytm_nonneg", "valuations", type_="check")
    op.drop_constraint("ck_valuation_price_positive", "valuations", type_="check")
    op.drop_constraint("ck_security_coupon_nonneg", "securities", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("securities", "interest_type")
    op.drop_index(op.f("ix_data_quality_checks_source"), table_name="data_quality_checks")
    op.drop_index(op.f("ix_data_quality_checks_run_date"), table_name="data_quality_checks")
    op.drop_index(op.f("ix_data_quality_checks_dataset"), table_name="data_quality_checks")
    op.drop_index(op.f("ix_data_quality_checks_check_name"), table_name="data_quality_checks")
    op.drop_table("data_quality_checks")
    # ### end Alembic commands ###
