"""public_issues table (SEBI)

Revision ID: 92fb5df8745f
Revises: 55fdc87faa72
Create Date: 2026-07-18 13:43:43.416415
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "92fb5df8745f"
down_revision: str | None = "55fdc87faa72"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "public_issues",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("company", sa.Text(), nullable=False),
        sa.Column("issue_open", sa.Date(), nullable=False),
        sa.Column("issue_close", sa.Date(), nullable=True),
        sa.Column("base_size_cr", sa.Float(), nullable=True),
        sa.Column("final_size_cr", sa.Float(), nullable=True),
        sa.Column("financial_year", sa.String(length=9), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column(
            "loaded_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company", "issue_open", "source", name="uq_public_issue"),
    )
    op.create_index(op.f("ix_public_issues_company"), "public_issues", ["company"], unique=False)
    op.create_index(
        op.f("ix_public_issues_financial_year"), "public_issues", ["financial_year"], unique=False
    )
    op.create_index(
        op.f("ix_public_issues_issue_open"), "public_issues", ["issue_open"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_public_issues_issue_open"), table_name="public_issues")
    op.drop_index(op.f("ix_public_issues_financial_year"), table_name="public_issues")
    op.drop_index(op.f("ix_public_issues_company"), table_name="public_issues")
    op.drop_table("public_issues")
    # ### end Alembic commands ###
