"""rbi_auctions table

Revision ID: bed81f16f24a
Revises: 92fb5df8745f
Create Date: 2026-07-18 13:51:22.764123
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "bed81f16f24a"
down_revision: str | None = "92fb5df8745f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rbi_auctions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("prid", sa.String(length=16), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("auction_type", sa.String(length=16), nullable=False),
        sa.Column("auction_date", sa.Date(), nullable=True),
        sa.Column("detail_url", sa.Text(), nullable=True),
        sa.Column("pdf_url", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("first_seen", sa.Date(), nullable=False),
        sa.Column("last_seen", sa.Date(), nullable=False),
        sa.Column(
            "loaded_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("prid", "source", name="uq_rbi_auction"),
    )
    op.create_index(
        op.f("ix_rbi_auctions_auction_date"), "rbi_auctions", ["auction_date"], unique=False
    )
    op.create_index(
        op.f("ix_rbi_auctions_auction_type"), "rbi_auctions", ["auction_type"], unique=False
    )
    op.create_index(op.f("ix_rbi_auctions_prid"), "rbi_auctions", ["prid"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rbi_auctions_prid"), table_name="rbi_auctions")
    op.drop_index(op.f("ix_rbi_auctions_auction_type"), table_name="rbi_auctions")
    op.drop_index(op.f("ix_rbi_auctions_auction_date"), table_name="rbi_auctions")
    op.drop_table("rbi_auctions")
    # ### end Alembic commands ###
