"""valuations bitemporal: append-only with superseded_at

A source restating a published price must not overwrite what we previously recorded.
The composite PK (isin, quote_date, source) becomes a *partial* unique index over
current rows only (superseded_at IS NULL); a surrogate id takes over as PK so closed
versions of the same key can coexist.

Revision ID: c9d4e7a1b2f3
Revises: b7e1a2c4d5f6
Create Date: 2026-07-27 12:45:00.000000
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c9d4e7a1b2f3"
down_revision: str | None = "b7e1a2c4d5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "valuations", sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True)
    )
    # Identity (not SERIAL) to match how Postgres backfills existing rows in one statement.
    op.execute("ALTER TABLE valuations ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY")
    op.drop_constraint("valuations_pkey", "valuations", type_="primary")
    op.create_primary_key("valuations_pkey", "valuations", ["id"])
    op.create_index(
        "uq_valuations_current",
        "valuations",
        ["isin", "quote_date", "source"],
        unique=True,
        postgresql_where=sa.text("superseded_at IS NULL"),
    )
    op.create_index(op.f("ix_valuations_isin"), "valuations", ["isin"], unique=False)


def downgrade() -> None:
    # Destructive: collapses history back to current-rows-only.
    op.execute("DELETE FROM valuations WHERE superseded_at IS NOT NULL")
    op.drop_index(op.f("ix_valuations_isin"), table_name="valuations")
    op.drop_index("uq_valuations_current", table_name="valuations")
    op.drop_constraint("valuations_pkey", "valuations", type_="primary")
    op.drop_column("valuations", "id")
    op.create_primary_key("valuations_pkey", "valuations", ["isin", "quote_date", "source"])
    op.drop_column("valuations", "superseded_at")
