"""etl_file_metrics table

Revision ID: e42c25cd4a00
Revises: 45cb274a85f3
Create Date: 2026-07-18 14:51:10.867229
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e42c25cd4a00"
down_revision: str | None = "45cb274a85f3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "etl_file_metrics",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("dataset", sa.String(length=48), nullable=False),
        sa.Column("run_date", sa.Date(), nullable=False),
        sa.Column("artifact", sa.String(length=64), nullable=False),
        sa.Column("bytes_downloaded", sa.BigInteger(), nullable=False),
        sa.Column("rows_extracted", sa.Integer(), nullable=False),
        sa.Column("rows_parsed", sa.Integer(), nullable=False),
        sa.Column("rows_dropped", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "dataset", "run_date", "artifact", name="uq_etl_file_metric"),
    )
    op.create_index(
        op.f("ix_etl_file_metrics_dataset"), "etl_file_metrics", ["dataset"], unique=False
    )
    op.create_index(
        op.f("ix_etl_file_metrics_run_date"), "etl_file_metrics", ["run_date"], unique=False
    )
    op.create_index(
        op.f("ix_etl_file_metrics_source"), "etl_file_metrics", ["source"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_etl_file_metrics_source"), table_name="etl_file_metrics")
    op.drop_index(op.f("ix_etl_file_metrics_run_date"), table_name="etl_file_metrics")
    op.drop_index(op.f("ix_etl_file_metrics_dataset"), table_name="etl_file_metrics")
    op.drop_table("etl_file_metrics")
    # ### end Alembic commands ###
